/* inftrees.c -- generate Huffman trees for efficient decoding
 * Copyright (C) 1995-2017 Mark Adler
 * For conditions of distribution and use, see copyright notice in zlib.h
 */

#include "zutil.h"
#include "inftrees.h"

#define MAXBITS 15

const char inflate_copyright[] =
   " inflate 1.2.11 Copyright 1995-2017 Mark Adler ";
/*
  If you use the zlib library in a product, an acknowledgment is welcome
  in the documentation of your product. If for some reason you cannot
  include such an acknowledgment, I would appreciate that you keep this
  copyright string in the executable of your product.
 */

/*
   Build a set of tables to decode the provided canonical Huffman code.
   The code lengths are codeLengths[0..symbolCount-1].  The result starts at *table,
   whose indices are 0..2^rootBitCount-1.  sortedSymbols is a writable array of at least
   codeLengths shorts, which is used as a work area.  type is the type of code
   to be generated, CODES, LENS, or DISTS.  On return, zero is success,
   -1 is an invalid code, and +1 means that ENOUGH isn't enough.  table
   on return points to the next available entry's address.  rootBitCount is the
   requested root table index bits, and on return it is the actual root
   table index bits.  It will differ if the request is greater than the
   longest code or if it is less than the shortest code.
 */
int ZLIB_INTERNAL inflate_table
    ( codetype            type
    , unsigned short FAR  *codeLengths
    , uint32_t            symbolCount
    , code FAR * FAR      *table
    , uint32_t FAR        *rootBitCount
    , unsigned short FAR  *sortedSymbols
    )
{
    uint32_t codeLength;               /* a code's length in bits */
    uint32_t iSymbol;               /* index of code symbols */
    uint32_t minimumCodeLength, maximumCodeLength;          /* minimum and maximum code lengths */
    uint32_t rootTableBits;              /* number of index bits for root table */
    uint32_t currentTableBits;              /* number of index bits for current table */
    uint32_t bitsToDrop;              /* code bits to drop for sub-table */
    int availablePrefixCodes;                   /* number of prefix codes available */
    uint32_t tableEntriesUsed;              /* code entries in table used */
    uint32_t huffmanCode;              /* Huffman code */
    uint32_t codeIncrement;              /* for incrementing code, index */
    uint32_t iReplicatedEntry;              /* index for replicating entries */
    uint32_t rootEntryBits;               /* low bits for current root entry */
    uint32_t rootTableMask;              /* mask for low rootTableBits bits */
    code currentEntry;                  /* table entry for duplication */
    code FAR *nextTable;             /* next available space in table */
    const unsigned short FAR *baseValues;     /* base value table to use */
    const unsigned short FAR *extraBitValues;    /* extra bits table to use */
    uint32_t firstMatchSymbol;             /* use base and extra for symbol >= match */
    unsigned short codeLengthCounts[MAXBITS+1];    /* number of codes of each length */
    unsigned short codeLengthOffsets[MAXBITS+1];     /* offsets in table for each length */
    static const unsigned short lengthBaseValues[31] = { /* Length codes 257..285 base */
        3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 15, 17, 19, 23, 27, 31,
        35, 43, 51, 59, 67, 83, 99, 115, 131, 163, 195, 227, 258, 0, 0};
    static const unsigned short lengthExtraBits[31] = { /* Length codes 257..285 extra */
        16, 16, 16, 16, 16, 16, 16, 16, 17, 17, 17, 17, 18, 18, 18, 18,
        19, 19, 19, 19, 20, 20, 20, 20, 21, 21, 21, 21, 16, 77, 202};
    static const unsigned short distanceBaseValues[32] = { /* Distance codes 0..29 base */
        1, 2, 3, 4, 5, 7, 9, 13, 17, 25, 33, 49, 65, 97, 129, 193,
        257, 385, 513, 769, 1025, 1537, 2049, 3073, 4097, 6145,
        8193, 12289, 16385, 24577, 0, 0};
    static const unsigned short distanceExtraBits[32] = { /* Distance codes 0..29 extra */
        16, 16, 16, 16, 17, 17, 18, 18, 19, 19, 20, 20, 21, 21, 22, 22,
        23, 23, 24, 24, 25, 25, 26, 26, 27, 27,
        28, 28, 29, 29, 64, 64};

    /*
       Process a set of code lengths to create a canonical Huffman code.  The
       code lengths are codeLengths[0..symbolCount-1].  Each length corresponds to the
       symbols 0..codes-1.  The Huffman code is generated by first sorting the
       symbols by length from short to long, and retaining the symbol order
       for codes with equal lengths.  Then the code starts with all zero bits
       for the first code of the shortest length, and the codes are integer
       increments for the same length, and zeros are appended as the length
       increases.  For the deflate format, these bits are stored backwards
       from their more natural integer increment ordering, and so when the
       decoding tables are built in the large loop below, the integer codes
       are incremented backwards.

       This routine assumes, but does not check, that all of the entries in
       codeLengths[] are in the range 0..MAXBITS.  The caller must assure this.
       1..MAXBITS is interpreted as that code length.  zero means that that
       symbol does not occur in this code.

       The codes are sorted by computing a count of codes for each length,
       creating from that a table of starting indices for each length in the
       sorted table, and then entering the symbols in order in the sorted
       table.  The sorted table is work[], with that space being provided by
       the caller.

       The length counts are used for other purposes as well, i.e. finding
       the minimum and maximum length codes, determining if there are any
       codes at all, checking for a valid set of lengths, and looking ahead
       at length counts to determine sub-table sizes when building the
       decoding tables.
     */

    /* accumulate lengths for codes (assumes codeLengths[] all in 0..MAXBITS) */
    for (codeLength = 0; codeLength <= MAXBITS; codeLength++)
        codeLengthCounts[codeLength] = 0;
    for (iSymbol = 0; iSymbol < symbolCount; iSymbol++)
        codeLengthCounts[codeLengths[iSymbol]]++;

    /* bound code lengths, force root to be within code lengths */
    rootTableBits = *rootBitCount;
    for (maximumCodeLength = MAXBITS; maximumCodeLength >= 1; maximumCodeLength--)
        if (codeLengthCounts[maximumCodeLength] != 0) break;
    if (rootTableBits > maximumCodeLength) rootTableBits = maximumCodeLength;
    if (maximumCodeLength == 0) {                     /* no symbols to code at all */
        currentEntry.op = (unsigned char)64;    /* invalid code marker */
        currentEntry.bits = (unsigned char)1;
        currentEntry.val = (unsigned short)0;
        *(*table)++ = currentEntry;             /* make a table to force an error */
        *(*table)++ = currentEntry;
        *rootBitCount = 1;
        return 0;     /* no symbols, but wait for decoding to report error */
    }
    for (minimumCodeLength = 1; minimumCodeLength < maximumCodeLength; minimumCodeLength++)
        if (codeLengthCounts[minimumCodeLength] != 0) break;
    if (rootTableBits < minimumCodeLength) rootTableBits = minimumCodeLength;

    /* check for an over-subscribed or incomplete set of lengths */
    availablePrefixCodes = 1;
    for (codeLength = 1; codeLength <= MAXBITS; codeLength++) {
        availablePrefixCodes <<= 1;
        availablePrefixCodes -= codeLengthCounts[codeLength];
        if (availablePrefixCodes < 0) return -1;        /* over-subscribed */
    }
    if (availablePrefixCodes > 0 && (type == CODES || maximumCodeLength != 1))
        return -1;                      /* incomplete set */

    /* generate offsets into symbol table for each length for sorting */
    codeLengthOffsets[1] = 0;
    for (codeLength = 1; codeLength < MAXBITS; codeLength++)
        codeLengthOffsets[codeLength + 1] = codeLengthOffsets[codeLength] + codeLengthCounts[codeLength];

    /* sort symbols by length, by symbol order within each length */
    for (iSymbol = 0; iSymbol < symbolCount; iSymbol++)
        if (codeLengths[iSymbol] != 0) sortedSymbols[codeLengthOffsets[codeLengths[iSymbol]]++] = (unsigned short)iSymbol;

    /*
       Create and fill in decoding tables.  In this loop, the table being
       filled is at nextTable and has currentTableBits index bits.  The code being used is huffmanCode
       with length codeLength.  That code is converted to an index by dropping bitsToDrop
       bits off of the bottom.  For codes where codeLength is less than bitsToDrop + currentTableBits,
       those top bitsToDrop + currentTableBits - codeLength bits are incremented through all values to
       fill the table with replicated entries.

       rootTableBits is the number of index bits for the root table.  When codeLength exceeds
       rootTableBits, sub-tables are created pointed to by the root entry with an index
       of the low rootTableBits bits of huffmanCode.  This is saved in rootEntryBits to check for when a
       new sub-table should be started.  bitsToDrop is zero when the root table is
       being filled, and bitsToDrop is rootTableBits when sub-tables are being filled.

       When a new sub-table is needed, it is necessary to look ahead in the
       code lengths to determine what size sub-table is needed.  The length
       counts are used for this, and so codeLengthCounts[] is decremented as codes are
       entered in the tables.

       tableEntriesUsed keeps track of how many table entries have been allocated from the
       provided *table space.  It is checked for LENS and DIST tables against
       the constants ENOUGH_LENS and ENOUGH_DISTS to guard against changes in
       the initial root table size constants.  See the comments in inftrees.h
       for more information.

       sym increments through all symbols, and the loop terminates when
       all codes of length maximumCodeLength, i.e. all codes, have been processed.  This
       routine permits incomplete codes, so another loop after this one fills
       in the rest of the decoding tables with invalid code markers.
     */

    /* set up for code type */
    switch (type) {
    case CODES:
        baseValues = extraBitValues = sortedSymbols;    /* dummy value--not used */
        firstMatchSymbol = 20;
        break;
    case LENS:
        baseValues = lengthBaseValues;
        extraBitValues = lengthExtraBits;
        firstMatchSymbol = 257;
        break;
    default:    /* DISTS */
        baseValues = distanceBaseValues;
        extraBitValues = distanceExtraBits;
        firstMatchSymbol = 0;
    }

    /* initialize state for loop */
    huffmanCode = 0;                   /* starting code */
    iSymbol = 0;                    /* starting code symbol */
    codeLength = minimumCodeLength;                  /* starting code length */
    nextTable = *table;              /* current table to fill in */
    currentTableBits = rootTableBits;                /* current table index bits */
    bitsToDrop = 0;                   /* current bits to drop from code for index */
    rootEntryBits = (uint32_t)(-1);       /* trigger new sub-table when codeLength > rootTableBits */
    tableEntriesUsed = 1U << rootTableBits;          /* use root table entries */
    rootTableMask = tableEntriesUsed - 1;            /* mask for comparing low */

    /* check available table space */
    if ((type == LENS && tableEntriesUsed > ENOUGH_LENS) ||
        (type == DISTS && tableEntriesUsed > ENOUGH_DISTS))
        return 1;

    /* process all codes and make table entries */
    for (;;) {
        /* create table entry */
        currentEntry.bits = (unsigned char)(codeLength - bitsToDrop);
        if (sortedSymbols[iSymbol] + 1U < firstMatchSymbol) {
            currentEntry.op = (unsigned char)0;
            currentEntry.val = sortedSymbols[iSymbol];
        }
        else if (sortedSymbols[iSymbol] >= firstMatchSymbol) {
            currentEntry.op = (unsigned char)(extraBitValues[sortedSymbols[iSymbol] - firstMatchSymbol]);
            currentEntry.val = baseValues[sortedSymbols[iSymbol] - firstMatchSymbol];
        }
        else {
            currentEntry.op = (unsigned char)(32 + 64);         /* end of block */
            currentEntry.val = 0;
        }

        /* replicate for those indices with low codeLength bits equal to huffmanCode */
        codeIncrement = 1U << (codeLength - bitsToDrop);
        iReplicatedEntry = 1U << currentTableBits;
        minimumCodeLength = iReplicatedEntry;                 /* save offset to next table */
        do {
            iReplicatedEntry -= codeIncrement;
            nextTable[(huffmanCode >> bitsToDrop) + iReplicatedEntry] = currentEntry;
        } while (iReplicatedEntry != 0);

        /* backwards increment the codeLength-bit code huffmanCode */
        codeIncrement = 1U << (codeLength - 1);
        while (huffmanCode & codeIncrement)
            codeIncrement >>= 1;
        if (codeIncrement != 0) {
            huffmanCode &= codeIncrement - 1;
            huffmanCode += codeIncrement;
        }
        else
            huffmanCode = 0;

        /* go to next symbol, update count, codeLength */
        iSymbol++;
        if (--(codeLengthCounts[codeLength]) == 0) {
            if (codeLength == maximumCodeLength) break;
            codeLength = codeLengths[sortedSymbols[iSymbol]];
        }

        /* create new sub-table if needed */
        if (codeLength > rootTableBits && (huffmanCode & rootTableMask) != rootEntryBits) {
            /* if first time, transition to sub-tables */
            if (bitsToDrop == 0)
                bitsToDrop = rootTableBits;

            /* increment past last table */
            nextTable += minimumCodeLength;            /* here minimumCodeLength is 1 << currentTableBits */

            /* determine length of next table */
            currentTableBits = codeLength - bitsToDrop;
            availablePrefixCodes = (int)(1 << currentTableBits);
            while (currentTableBits + bitsToDrop < maximumCodeLength) {
                availablePrefixCodes -= codeLengthCounts[currentTableBits + bitsToDrop];
                if (availablePrefixCodes <= 0) break;
                currentTableBits++;
                availablePrefixCodes <<= 1;
            }

            /* check for enough space */
            tableEntriesUsed += 1U << currentTableBits;
            if ((type == LENS && tableEntriesUsed > ENOUGH_LENS) ||
                (type == DISTS && tableEntriesUsed > ENOUGH_DISTS))
                return 1;

            /* point entry in root table to sub-table */
            rootEntryBits = huffmanCode & rootTableMask;
            (*table)[rootEntryBits].op = (unsigned char)currentTableBits;
            (*table)[rootEntryBits].bits = (unsigned char)rootTableBits;
            (*table)[rootEntryBits].val = (unsigned short)(nextTable - *table);
        }
    }

    /* fill in remaining table entry if code is incomplete (guaranteed to have at most one remaining entry, since if the code is incomplete, the maximum code length that was allowed to get this far is one bit) */
    if (huffmanCode != 0) {
        currentEntry.op = (unsigned char)64;            /* invalid code marker */
        currentEntry.bits = (unsigned char)(codeLength - bitsToDrop);
        currentEntry.val = (unsigned short)0;
        nextTable[huffmanCode] = currentEntry;
    }

    /* set return parameters */
    *table += tableEntriesUsed;
    *rootBitCount = rootTableBits;
    return 0;
}
